import Head from 'next/head'
import { Box, Text, Grid, SimpleGrid, Flex } from "@chakra-ui/react"


import { Link } from '@chakra-ui/next-js'

export default function test1() {

    const demo = [1, 2, 3, 4, 5];


    const basicBoxStyles = {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        boxSize: '250px',
        color: 'white',
        textShadow: '0 0 20px black',
        fontWeight: 'bold',
        fontSize: '20px',
        px: 4,
        background:
            'url(https://picsum.photos/id/1080/200/300) center/cover no-repeat',
    }


    const outerBoxStyles = {
        boxSize: '250px',
        p: '10',
        background:
            'url(https://picsum.photos/id/1068/200/300) center/cover no-repeat',
    }

    const innerBoxStyles = {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        boxSize: 'full',
        color: 'white',
        textShadow: '0 0 20px black',
        fontWeight: 'bold',
        fontSize: '20px',
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h3>Hello, World</h3>

                <Link
                    href='/about'
                    color='red.400'
                    _hover={{ color: 'blue.500' }}
                >
                    About
                </Link>


                <Box
                    m={3}
                    bgGradient="linear(to-t, red.200, blue.500)"
                    color={"white"}
                    bgClip="text"
                    fontSize={"3xl"}
                    fontWeight={"extrabold"}
                >
                    Taste
                </Box>


                <Text
                    bgGradient="linear(to-l, #7928CA, #fbd7e9)"
                    bgClip="text"
                    fontSize="6xl"
                    fontWeight="extrabold"
                >
                    Welcome to Chakra UI
                </Text>

                <SimpleGrid
                    bg='gray.50'
                    columns={{ sm: 2, md: 4 }}
                    minH={'300px'}
                    spacing='8'
                    p='10'
                    textAlign='center'
                    rounded='lg'
                    color='gray.400'
                >
                    {demo.map((item, index) => {
                        return (<Grid textAlign={"center"} alignItems={"center"} bg={index % 2 == 0 ? "red" : "green"} key={item} gap={2} >
                            Grid
                        </Grid>
                        )
                    }
                    )}

                    <Box
                        textAlign={"center"}
                        alignItems={"center"}
                        boxShadow='md' p='6' rounded='md' bg='white' color={"black"} fontWeight={"bold"}>
                        Medium
                    </Box>
                </SimpleGrid>

                <Text textShadow='1px 2px blue' m='6'>
                    Text with shadows
                </Text>


                <Flex flexWrap='wrap' gap='24px' justifyContent='space-evenly'>
                    {/* adding filter property to the element */}
                    <Box sx={basicBoxStyles} filter='grayscale(60%)'>
                        Box with Filter
                    </Box>
                    {/* adding blur property to the element */}
                    <Box sx={basicBoxStyles} filter='auto' blur='2px'>
                        Box with Blur
                    </Box>
                    {/* adding brightness property to the element */}
                    <Box sx={basicBoxStyles} filter='auto' brightness='40%'>
                        Box with Brightness
                    </Box>
                </Flex>


                <Flex flexWrap='wrap' gap='24px' justifyContent='space-evenly'>
                    {/* adding backdrop-filter property to the element */}
                    <Box sx={outerBoxStyles}>
                        <Box sx={innerBoxStyles} backdropFilter='invert(10%)'>
                            Box with Backdrop Filter
                        </Box>
                    </Box>
                    {/* adding backdrop-blur property to the element */}
                    <Box sx={outerBoxStyles}>
                        <Box sx={innerBoxStyles} backdropFilter='auto' backdropBlur='8px'>
                            Box with Backdrop Blur
                        </Box>
                    </Box>
                    {/* adding backdrop-contrast property to the element */}
                    <Box sx={outerBoxStyles}>
                        <Box sx={innerBoxStyles} backdropFilter='auto' backdropContrast='30%'>
                            Box with Backdrop Contrast
                        </Box>
                    </Box>
                </Flex>


                <Box
                    draggable
                    _grabbed={{ color: "red" }}
                    _before={{ content: '"🙂"', display: 'inline-block', mr: '5px' }}
                >
                    A pseudo element
                </Box>
            </main>
        </>
    )
}
